// Central icon exports (professional, consistent set)
// Uses lucide icons via react-icons.
import {
  LuArrowLeft,
  LuBadgeCheck,
  LuBan,
  LuCalendarDays,
  LuCar,
  LuCheck,
  LuChevronLeft,
  LuChevronRight,
  LuClipboardList,
  LuClock,
  LuCopy,
  LuCreditCard,
  LuExternalLink,
  LuFileText,
  LuGlobe,
  LuHotel,
  LuLink,
  LuLock,
  LuMail,
  LuMapPin,
  LuMessageCircle,
  LuMinus,
  LuPenLine,
  LuPhone,
  LuPlane,
  LuPlus,
  LuSearch,
  LuShare2,
  LuShieldCheck,
  LuSmartphone,
  LuSparkles,
  LuStar,
  LuTrash2,
  LuTriangleAlert,
  LuUser,
  LuX,
  LuUtensils,
  LuMap,
  LuBusFront,
  LuTrainFront,
  LuMusic,
  LuTreePalm,
  LuShoppingBag,
  LuMountain,
  LuTicket,
  LuInfo,
  LuCompass,
  LuLandmark,
  LuBriefcase,
  LuCircleDollarSign,
  LuShip,
  LuActivity,
  LuCamera,
  LuFlame,
  LuHeart,
  LuPartyPopper,
  LuThumbsUp,
  LuSmile,
  LuNotebook,
  LuCircleEllipsis,
  LuCloud,
  LuBell,
} from 'react-icons/lu';

export const Icons = {
  ArrowLeft: LuArrowLeft,
  BadgeCheck: LuBadgeCheck,
  Ban: LuBan,
  Calendar: LuCalendarDays,
  Car: LuCar,
  Check: LuCheck,
  ChevronLeft: LuChevronLeft,
  ChevronRight: LuChevronRight,
  Checklist: LuClipboardList,
  Clock: LuClock,
  Copy: LuCopy,
  CreditCard: LuCreditCard,
  ExternalLink: LuExternalLink,
  FileText: LuFileText,
  Globe: LuGlobe,
  Hotel: LuHotel,
  Link: LuLink,
  Lock: LuLock,
  Mail: LuMail,
  MapPin: LuMapPin,
  Message: LuMessageCircle,
  Minus: LuMinus,
  Note: LuPenLine,
  Phone: LuPhone,
  Plane: LuPlane,
  Plus: LuPlus,
  Search: LuSearch,
  Share: LuShare2,
  ShieldCheck: LuShieldCheck,
  Smartphone: LuSmartphone,
  Sparkles: LuSparkles,
  Star: LuStar,
  Trash: LuTrash2,
  Warning: LuTriangleAlert,
  User: LuUser,
  X: LuX,
  Utensils: LuUtensils,
  Map: LuMap,
  Bus: LuBusFront,
  Train: LuTrainFront,
  Music: LuMusic,
  PalmTree: LuTreePalm,
  ShoppingBag: LuShoppingBag,
  Mountain: LuMountain,
  Ticket: LuTicket,
  Info: LuInfo,
  Compass: LuCompass,
  Landmark: LuLandmark,
  Briefcase: LuBriefcase,
  Dollar: LuCircleDollarSign,
  Ship: LuShip,
  Activity: LuActivity,
  Camera: LuCamera,
  Flame: LuFlame,
  Heart: LuHeart,
  Party: LuPartyPopper,
  ThumbsUp: LuThumbsUp,
  Smile: LuSmile,
  Notebook: LuNotebook,
  More: LuCircleEllipsis,
  Cloud: LuCloud,
  Bell: LuBell,
};

