// Central icon exports (professional, consistent set)
// Uses lucide icons via react-icons.
import {
  LuArrowLeft,
  LuBadgeCheck,
  LuBan,
  LuCalendarDays,
  LuCar,
  LuCheck,
  LuChevronLeft,
  LuChevronRight,
  LuClipboardList,
  LuClock,
  LuCopy,
  LuCreditCard,
  LuExternalLink,
  LuFileText,
  LuGlobe,
  LuHotel,
  LuLink,
  LuLock,
  LuMail,
  LuMapPin,
  LuMessageCircle,
  LuMinus,
  LuPenLine,
  LuPhone,
  LuPlane,
  LuPlus,
  LuSearch,
  LuShare2,
  LuShieldCheck,
  LuSmartphone,
  LuSparkles,
  LuStar,
  LuTrash2,
  LuTriangleAlert,
  LuUser,
  LuX,
} from 'react-icons/lu';

export const Icons = {
  ArrowLeft: LuArrowLeft,
  BadgeCheck: LuBadgeCheck,
  Ban: LuBan,
  Calendar: LuCalendarDays,
  Car: LuCar,
  Check: LuCheck,
  ChevronLeft: LuChevronLeft,
  ChevronRight: LuChevronRight,
  Checklist: LuClipboardList,
  Clock: LuClock,
  Copy: LuCopy,
  CreditCard: LuCreditCard,
  ExternalLink: LuExternalLink,
  FileText: LuFileText,
  Globe: LuGlobe,
  Hotel: LuHotel,
  Link: LuLink,
  Lock: LuLock,
  Mail: LuMail,
  MapPin: LuMapPin,
  Message: LuMessageCircle,
  Minus: LuMinus,
  Note: LuPenLine,
  Phone: LuPhone,
  Plane: LuPlane,
  Plus: LuPlus,
  Search: LuSearch,
  Share: LuShare2,
  ShieldCheck: LuShieldCheck,
  Smartphone: LuSmartphone,
  Sparkles: LuSparkles,
  Star: LuStar,
  Trash: LuTrash2,
  Warning: LuTriangleAlert,
  User: LuUser,
  X: LuX,
};

